/**
 * Fruit Database api
 * Random api that returns fruits
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FruitSchemaNutritions {
  carbohydrates?: number;
  protein?: number;
  fat?: number;
  calories?: number;
  sugar?: number;
}
